"""empty message

Revision ID: 5576bc5db5da
Revises: 
Create Date: 2019-03-08 16:12:59.285452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5576bc5db5da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_form_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('报表名称', sa.String(length=64), nullable=True),
    sa.Column('报表需求方', sa.String(length=64), nullable=True),
    sa.Column('需求描述', sa.String(length=64), nullable=True),
    sa.Column('周期', sa.String(length=64), nullable=True),
    sa.Column('执行时间', sa.String(length=30), nullable=True),
    sa.Column('crontabTime', sa.String(length=255), nullable=True),
    sa.Column('脚本路径', sa.String(length=80), nullable=True),
    sa.Column('收件人', sa.Text(), nullable=True),
    sa.Column('delete_flag', sa.Integer(), server_default='0', nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default='0000-00-00 00:00:00', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_form_record')
    # ### end Alembic commands ###
